In [109]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("vectorized version: "+str(1000*(toc-tic))+"ms")


c = 0
tic =time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc =time.time()
print(c)
print("for loop: "+str(1000*(toc-tic))+"ms")

249456.45144278192
vectorized version: 1.1515617370605469ms
249456.4514427748
for loop: 284.3210697174072ms


In [15]:
a = np.random.rand(10000,10000)
b = np.random.rand(10000)

print(a.shape)
print(b.shape)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("vectorized version: "+str(1000*(toc-tic))+"ms")

tic = time.time()
d = np.abs(a)
toc = time.time()
print(d)
print("vectorized version: "+str(1000*(toc-tic))+"ms")

(10000, 10000)
(10000,)
[2508.1099576  2480.03489749 2467.79128074 ... 2530.20952076 2502.27853526
 2527.55627547]
vectorized version: 46.87356948852539ms
[[0.48365551 0.63159114 0.9449808  ... 0.43546739 0.38756564 0.71133002]
 [0.16939323 0.67437183 0.26461024 ... 0.15927956 0.49860523 0.7889601 ]
 [0.67698676 0.00721493 0.792051   ... 0.27840249 0.17932397 0.05073057]
 ...
 [0.17060365 0.5577743  0.97442424 ... 0.43393034 0.51541551 0.92233701]
 [0.84405634 0.83881726 0.31398948 ... 0.91852061 0.1993068  0.39870452]
 [0.06176452 0.97914673 0.41929626 ... 0.76283607 0.03734074 0.45888716]]
vectorized version: 150.9377956390381ms


In [18]:
a.max(axis=1)

array([0.99976614, 0.99997715, 0.99999828, ..., 0.99996259, 0.99996691,
       0.9999433 ])

In [111]:
from sklearn.datasets import make_blobs
train_x, train_y = make_blobs(n_samples=1000, centers=2, n_features=100,random_state=0)
train_x = train_x.T
#train = np.random.rand(100,1000) # (features,number of examples)
#test = np.random.randint(0,2,1000)
alpha = 0.1
itr = 10000
def sigma(x):
    return 1 / (1 + np.exp(-x))
def logistic_regression(train,test,alpha,itr):
    n,m=train.shape
    W = np.zeros((n,1))
    b = 0
    for i in range(itr):
        z = np.dot(W.T,train) + b
        a = sigma(z)
        dz = a-test
        dw = np.dot(train,dz.T)/m
        db = np.sum(dz)/m
        W = W - (dw*alpha)
        b = b - (db*alpha)
    pred = []
    print(a.shape)
    for i in a.T:
        #print(i)
        if i[0]>0.5:
            pred.append(1)
        else:
            pred.append(0)
    return pred
pred = logistic_regression(train_x,train_y,alpha,itr)

#pd.concat([pd.DataFrame(test),pd.DataFrame(pred)],axis=1)

(1, 1000)


In [119]:
class logistic_regression():
    def __init__(self,alpha=0.1,itr = 100):
        self.alpha = alpha
        self.itr = itr
        
    def sigma(self,x):
        return 1 / (1 + np.exp(-x))
    
    def fit(self,X,y):
        n,m=X.shape
        W = np.zeros((n,1))
        b = 0
        for i in range(self.itr):
            z = np.dot(W.T,X) + b
            a = sigma(z)
            dz = a-y
            dw = np.dot(X,dz.T)/m
            db = np.sum(dz)/m
            W = W - (dw*self.alpha)
            b = b - (db*self.alpha)
        self.W = W
        self.b = b
    
    def predict(self,train):
        z = np.dot(self.W.T,train) + self.b
        a = sigma(z)
        pred = []
        for i in a.T:
            if i[0]>0.5:
                pred.append(1)
            else:
                pred.append(0)
        return pred

In [125]:
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
data, label = make_blobs(n_samples=5000, centers=2, n_features=100,random_state=0)
train_x,test_x,train_y,test_Y = train_test_split(data,label,test_size=0.25)
train_x = train_x.T
test_x = test_x.T
model = logistic_regression()
model.fit(train_x,train_y)
prediction = model.predict(test_x)

In [128]:
#pd.concat([pd.DataFrame(test_Y),pd.DataFrame(prediction)],axis=1)
from sklearn.metrics import accuracy_score
accuracy_score(test_Y,prediction)

1.0

In [141]:
import os
import cv2
import random
training_data = []
img_size = 50
d_path = 'keras_tutorials/dogs-vs-cats'
categories = ['Dog','Cat']
def create_training_data():
    for c in categories:
        path = os.path.join(d_path,c)
        for img in os.listdir(path):
            try:
                class_num = categories.index(c)
                img_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
                #img_array = img_array[:, :, ::-1]
                new_image = cv2.resize(img_array,(img_size,img_size))
                training_data.append([new_image,class_num])
            except Exception as e:
                pass
create_training_data()
random.shuffle(training_data)
x = []
y = []
for feature, label in training_data:
    x.append(feature)
    y.append(label)

In [162]:
X = []
for i in x:
    X.append(i.flatten())
X = np.array(X)

In [ ]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_Y = train_test_split(X,y,test_size=0.25)
train_x = train_x.T
test_x = test_x.T
model = logistic_regression(itr = 1000)
model.fit(train_x,train_y)
prediction = model.predict(test_x)

In [167]:
from sklearn.metrics import accuracy_score
accuracy_score(test_Y,prediction)

0.49296